name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
      with:
        fetch-depth: '0'
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        WITH_V: true
        INITIAL_VERSION: 0.1.0
        TAG_CONTEXT: repo
        PRERELEASE_SUFFIX: beta
        VERBOSE: true
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        artifactErrorsFailBuild: true
        generateReleaseNotes: true
        omitBodyDuringUpdate: true
        omitPrereleaseDuringUpdate: true
        replacesArtifacts: true
        omitNameDuringUpdate: true
